### ISSUE TITLE
headerfile not found

### ISSUE THREAD

**Issue by HARSH-SHETH** [Mayurji/Understanding-Search-Engine-Using-Cplusplus#1]
While compiling the Mini_Search_Engine.cpp file I get error: 
> Mini_Search_Engine.cpp:19:10: fatal error: CoreFoundation/CFBundle.h: No such file or directory
> #include <CoreFoundation/CFBundle.h>

 Would you please upload the following files: `CoreFoundation/CFBundle.h` and `ApplicationServices/ApplicationServices.h`

**Comment by Mayurji** [comment]
Can you share the config of your system ?

**Comment by HARSH-SHETH** [comment]
> Can you share the config of your system ?

What details do you need exactly ? 
I am currently using `Ubuntu 18.04 LTS`  version 
g++ version : `7.5.0`

**Comment by Mayurji** [comment]
Those packages are meant for MacOS. Kindly refer the pre-requisite to run the script directly.

**Comment by HARSH-SHETH** [comment]
I want to make a search engine like this on my own, After reading the readme I still have doubt about its working procedure, 
For ex: If a user enters: `cool wallpapers` as a search query then the program will search the sentences in the `General_Problems.txt` and will find the sentences which have the keywords `cool` or `wallpapers` or both. Then, it will fetch the url from `General_Solutions.txt` at the index which matches the index of the sentence found in the `General_Problems.txt` and will open that url in the browser. 

#### Is my perception right or am I missing something ?

**Comment by Mayurji** [comment]
Yes that's exactly right. That's the flow.

**Comment by HARSH-SHETH** [comment]
**Thanks for replying.** :heart:
